version: "3.9"
services:
  wss:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
      - REDIS_HOST=redis
    depends_on:
      - redis
  redis:
    image: "redis:alpine"